### ISSUE TITLE
Add script for use with PM2

### ISSUE THREAD

**Issue by micahwalter** [mplusmuseum/mplusmuseum-graphql#10]

**Comment by micahwalter** [comment]
Seems like this is just missing some babel related dependancies to allow it to `yarn serve` ...

**Comment by revdancatt** [comment]
Need more definition.

**Comment by jedahan** [comment]
I think this is like, creating an `ecosystem.json` file. I haven't used pm2 extensively, but its to make sure we can reproduce the commandline version of just `pm2 start some/path/to/main.js`

**Comment by micahwalter** [comment]
basically we need a way to start/restart the process in PM2

also, need to know what CodeDeploy should run as part of this script ( this is the script that CodeDeploy will run after updating the code )

https://github.com/mplusmuseum/mplusmuseum-graphql/blob/master/ubuntu/post-deploy.sh#L7-L10

**Comment by micahwalter** [comment]
This is basically done.

    $ pm2 start build/index.js --name "mplusmuseum-graphql"
