### ISSUE TITLE
API user authentication

### ISSUE THREAD

**Issue by rnackman** [mplusmuseum/mplusmuseum-graphql#2]

**Comment by micahwalter** [comment]
Username/Password auth for now.

**Comment by micahwalter** [comment]
I'll leave this open for future proper API auth

**Comment by micahwalter** [comment]
OK @revdancatt lets start with using Auth0 for all of our Auth needs on this site ( the API  ) and over on www.

**Comment by revdancatt** [comment]
This has been superseded by #45
