### ISSUE TITLE
Permissions things

### ISSUE THREAD

**Issue by micahwalter** [mplusmuseum/mplusmuseum-graphql#44]
Using Auth0 ( if possible ) set up permissions within the API for

- Users - User level permissions
- Roles - Groups of users like admin, staff, etc..
- Keys - Key level permissions for things like apps, sites, etc.

We need to store all that data somewhere and have a way to manage it - assign users to roles, etc. in the admin area, lists of users, list of keys, etc.

**Comment by revdancatt** [comment]
All this is handled over at the dashboard now. Well _most_ of it.
